import assert from "node:assert/strict";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { spawn } from "node:child_process";
import { chromium } from "playwright-core";

const target = new URL(process.env.DATABASE_URL || "http://missing");
assert.equal(target.hostname, "127.0.0.1");
assert.equal(target.port, "15436");
assert.match(target.pathname, /^\/lab_resources_open_lab_test_[a-z0-9_]+$/);
Object.assign(process.env, { NODE_ENV: "test", JWT_SECRET: "open-lab-isolated-test-secret-only", LOG_FORMAT: "dev", CORS_ORIGINS: "http://127.0.0.1:15181", PAYMENTS_ENABLED: "true", MCP_ASSISTANT_ENABLED: "false", RATE_LIMIT_MAX: "5000", VNPAY_ENABLED: "true", VNPAY_TMN_CODE: "TESTQR12", VNPAY_HASH_SECRET: "isolated-browser-test-secret", VNPAY_RETURN_URL: "http://127.0.0.1:15006/api/payments/vnpay/return", VNPAY_IPN_URL: "http://127.0.0.1:15006/api/payments/vnpay/ipn" });
const requireBackend = createRequire(new URL("../backend/package.json", import.meta.url));
const jwt = requireBackend("jsonwebtoken");
const { createApp } = await import("../backend/src/app.js");
const { prisma } = await import("../backend/src/db.js");
const server = createApp().listen(15006, "127.0.0.1");
await new Promise(resolve => server.once("listening", resolve));
const vite = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", "15181", "--strictPort"], { cwd: new URL("./", import.meta.url), env: { ...process.env, VITE_API_BASE_URL: "http://127.0.0.1:15006/api", VITE_ENABLE_PAYMENT_FEATURES: "true" }, windowsHide: true, stdio: "ignore" });
const out = new URL("./screenshots_temp_open_lab/", import.meta.url);
fs.mkdirSync(out, { recursive: true });
let browser;
try {
  let ready = false;
  for (let n = 0; n < 50; n++) {
    try { if ((await fetch("http://127.0.0.1:15181")).ok) { ready = true; break; } } catch { /* Startup only. */ }
    await new Promise(resolve => setTimeout(resolve, 200));
  }
  assert.ok(ready, "Vite did not start");
  browser = await chromium.launch({ headless: true });
  const errors = [];
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on("pageerror", error => errors.push(error.message));
  async function signIn(id, role, route) {
    const token = jwt.sign({ sub: id, role }, process.env.JWT_SECRET, { algorithm: "HS256" });
    await page.goto("http://127.0.0.1:15181");
    await page.evaluate(token => localStorage.setItem("lrm_token", token), token);
    await page.goto(`http://127.0.0.1:15181${route}`);
    await page.reload({ waitUntil: "networkidle" });
  }
  await signIn("admin", "ADMIN", "#dang-nhap");
  await page.locator(".workspace-home").waitFor();
  assert.match(page.url(), /#\/workspace\/tong-quan$/);
  await page.locator(".sidebar-nav-item-2026", { hasText: "Bảng Điều Khiển Vận Hành" }).click();
  await page.getByRole("heading", { name: "Mức sử dụng 30 ngày", exact: true }).waitFor();
  assert.match(page.url(), /#\/workspace\/van-hanh$/);
  assert.equal(await page.getByRole("heading", { name: "Trạng thái telemetry", exact: true }).count(), 0);
  await page.screenshot({ path: fileURLToPath(new URL("operations-desktop.png", out)), animations: "disabled" });
  await page.locator(".sidebar-nav-item-2026", { hasText: "Giám Sát Telemetry" }).click();
  await page.getByRole("heading", { name: "Trạng thái telemetry", exact: true }).waitFor();
  assert.equal(await page.getByRole("heading", { name: "Mức sử dụng 30 ngày", exact: true }).count(), 0);
  await page.reload({ waitUntil: "networkidle" });
  await page.getByRole("heading", { name: "Giám sát telemetry", exact: true }).waitFor();
  await page.goBack({ waitUntil: "networkidle" });
  await page.getByRole("heading", { name: "Mức sử dụng 30 ngày", exact: true }).waitFor();
  await page.goForward({ waitUntil: "networkidle" });
  await page.getByRole("heading", { name: "Trạng thái telemetry", exact: true }).waitFor();
  await page.screenshot({ path: fileURLToPath(new URL("telemetry-desktop.png", out)), animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.screenshot({ path: fileURLToPath(new URL("telemetry-mobile.png", out)), animations: "disabled" });

  const { transitionBooking, createBooking } = await import("../backend/src/services/bookingService.js");
  const { cancelBooking } = await import("../backend/src/services/bookingService.js");
  for (const pending of await prisma.booking.findMany({ where: { resourceId: "room", status: "PENDING_APPROVAL" } })) await cancelBooking(pending.id, "admin", "ADMIN", "Isolated UI fixture cleanup");
  const booking = await createBooking({ requestedById: "other", resourceId: "room", title: "Browser self-return test", purpose: "Isolated test", startAt: new Date(Date.now() + 3600000), endAt: new Date(Date.now() + 7200000) });
  await transitionBooking({ bookingId: booking.id, toStatus: "CONFIRMED", actorId: "admin", actorRole: "ADMIN" });
  await transitionBooking({ bookingId: booking.id, toStatus: "CHECKED_OUT", actorId: "staff", actorRole: "LAB_STAFF", conditionBefore: "Browser fixture condition" });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await signIn("other", "LECTURER", `#/workspace/booking?booking=${booking.id}`);
  await page.getByRole("button", { name: "Trả phòng và hoàn tất", exact: true }).click();
  await page.locator("#booking-condition-evidence").fill("Đã rời phòng, tắt thiết bị, bàn ghế nguyên vẹn.");
  await page.screenshot({ path: fileURLToPath(new URL("self-return-evidence.png", out)), animations: "disabled" });
  await page.getByRole("button", { name: "Xác nhận trả phòng", exact: true }).click();
  await page.getByText(/Đã cập nhật booking.*hoàn tất/).waitFor();
  assert.equal((await prisma.booking.findUnique({ where: { id: booking.id } })).status, "COMPLETED");
  await page.getByRole("link", { name: "Xem tất cả lịch đặt" }).click();
  await page.getByRole("heading", { name: "Lịch đặt và tiến trình sử dụng của tôi" }).waitFor();
  await page.goto("http://127.0.0.1:15181/#/workspace/nguoi-dung", { waitUntil: "networkidle" });
  await page.waitForURL("**/#/workspace/lich-dat");
  assert.doesNotMatch(page.url(), /nguoi-dung$/);
  await prisma.resource.upsert({ where: { id: "ui-priced" }, update: {}, create: { id: "ui-priced", code: "UI-PRICED", name: "UI priced ROOM", category: "ROOM", subtype: "ROOM", location: "test", laboratoryId: "lab", requiresApproval: false } });
  await signIn("admin", "ADMIN", "#/workspace/thanh-toan");
  await page.getByText("Bảng giá tài nguyên theo mục đích", { exact: true }).click();
  await page.getByLabel("Tài nguyên tính phí", { exact: true }).selectOption("ui-priced");
  await page.getByLabel("Đơn giá VND / giờ").fill("60000");
  await page.getByRole("button", { name: "Lưu mức phí", exact: true }).click();
  await page.getByText("Đã lưu bảng giá. Mức phí của booking đã tạo được giữ nguyên.").waitFor();
  const freeBooking = await prisma.booking.findFirstOrThrow({ where: { requestedById: "owner", resourceId: "room", feeAmountVnd: 0 } });
  await signIn("owner", "STUDENT", `#/workspace/thanh-toan?booking=${freeBooking.id}`);
  await page.getByText(/Lịch đặt này không có phí sử dụng/).waitFor();
  assert.equal(await page.getByRole("button", { name: /Thanh toán.*VNPAY-QR/ }).count(), 0);
  await page.screenshot({ path: fileURLToPath(new URL("booking-free.png", out)), animations: "disabled" });
  await signIn("owner", "STUDENT", "#/workspace/lich-dat");
  await page.locator("#calendar-resource-select").selectOption("ui-priced");
  await page.getByRole("button", { name: "Đặt Khung Giờ Mới", exact: true }).click();
  await page.locator("#booking-title").fill("Paid room UI test");
  await page.locator("#booking-purpose").fill("Study fixture");
  await page.locator("#booking-date").fill(new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10));
  await page.locator("#booking-start-time").fill("09:00");
  await page.locator("#booking-end-time").fill("10:30");
  await page.getByText("90.000 đ", { exact: true }).waitFor();
  await page.screenshot({ path: fileURLToPath(new URL("pricing-quote.png", out)), animations: "disabled" });
  const posted = page.waitForResponse(r => r.url().endsWith("/api/bookings") && r.request().method() === "POST");
  await page.getByRole("button", { name: "Xác nhận đặt lịch", exact: true }).click();
  const response = await posted;
  assert.equal(response.status(), 201);
  const paidBooking = await response.json();
  assert.equal(paidBooking.feeAmountVnd, 90000);
  assert.equal(paidBooking.status, "CONFIRMED");
  assert.equal(await prisma.paymentTransaction.count({ where: { bookingId: paidBooking.id, amount: 90000, status: "pending" } }), 1);
  await page.getByRole("heading", { name: "Thanh toán đặt phòng LAB", exact: true }).waitFor();
  assert.match(page.url(), new RegExp(`booking=${paidBooking.id}$`));
  await page.getByText("90.000 ₫", { exact: true }).first().waitFor();
  await page.getByRole("button", { name: /Thanh toán 90.000 ₫ qua VNPAY-QR/ }).waitFor();
  await page.screenshot({ path: fileURLToPath(new URL("booking-payment.png", out)), animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), "Checkout overflows on mobile");
  await page.screenshot({ path: fileURLToPath(new URL("booking-payment-mobile.png", out)), animations: "disabled" });
  await page.setViewportSize({ width: 1440, height: 1000 });
  let gatewayUrl = "";
  await page.route("https://sandbox.vnpayment.vn/**", async route => {
    gatewayUrl = route.request().url();
    await route.fulfill({ status: 200, contentType: "text/html", body: "<h1>Gateway test interception only</h1>" });
  });
  await page.getByRole("button", { name: /Thanh toán 90.000 ₫ qua VNPAY-QR/ }).click();
  await page.getByRole("heading", { name: "Gateway test interception only" }).waitFor();
  const gateway = new URL(gatewayUrl);
  assert.equal(gateway.searchParams.get("vnp_BankCode"), "VNPAYQR");
  assert.equal(gateway.searchParams.get("vnp_Amount"), "9000000");
  assert.match(gateway.searchParams.get("vnp_SecureHash") || "", /^[a-f0-9]{128}$/);
  assert.deepEqual(errors, []);
  fs.writeFileSync(new URL("browser-results.json", out), JSON.stringify({ status: "PASS", checks: ["route login/navigation/reload/back/forward", "operations vs telemetry", "mobile overflow", "real owner ROOM return from UI", "booking deep link and clear", "role route guard", "admin pricing UI", "quote / create / direct checkout / VNPAYQR redirect"], pageErrors: errors }, null, 2));
  console.log("Open LAB operations browser checks PASS");
} finally {
  await browser?.close();
  vite.kill();
  server.close();
  await prisma.$disconnect();
}
