import { openWorkspace } from "./test-utils/openWorkspace.mjs";
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { chromium } from 'playwright-core';
// Isolated UI contract fixtures; no requests reach a real API or media store.
const base = process.env.UI_BASE_URL || 'http://127.0.0.1:5173';
const screenshots = process.env.UI_SCREENSHOT_DIR || 'logs/resource-dossier';
mkdirSync(screenshots, { recursive: true });
const fixture = { id:'equipment-a', code:'CAM-01', name:'Camera thực hành — dữ liệu kiểm thử', category:'EQUIPMENT', subtype:'CAMERA', location:'LAB 101', capacity:1, bookingState:'bookable', operationalStatus:'AVAILABLE', effectiveRequiresApproval:true, manufacturer:'Fixture', model:'QA-01', description:'Thiết bị kiểm thử giao diện. Không phải hướng dẫn vận hành một model thực tế.', laboratoryId:'lab-a', laboratory:{id:'lab-a',code:'LAB',name:'Phòng thực hành', labPolicy:{workDayStartHour:0,workDayEndHour:18,requiresApproval:true}}, specs:{resolution:'24 MP', usageGuide:{beforeUse:['Kiểm tra phụ kiện cùng cán bộ.'], steps:['Làm theo hướng dẫn đã được xác minh của thiết bị.'], afterUse:['Ghi nhận tình trạng khi hoàn trả.'],safetyNotes:'Dừng thao tác nếu có bất thường.\nBáo cán bộ LAB.'}}, media:[{id:'image-a',kind:'IMAGE',url:`${base}/qa-image.svg`,title:'Ảnh tổng thể',altText:'Ảnh thiết bị kiểm thử'},{id:'video-a',kind:'VIDEO',url:`${base}/qa-video.mp4`,title:'Video hướng dẫn',altText:'Video kiểm thử'}],trainingRequirements:[],availability:{state:'AVAILABLE'},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString() };
const blocked={...fixture,id:'equipment-b',code:'CAM-02',name:'Thiết bị hạn chế — dữ liệu kiểm thử',bookingState:'restricted',specs:{},media:[]};
const admin={id:'admin-qa',fullName:'Admin kiểm thử',email:'qa@example.test',role:'ADMIN',isActive:true};
let patches=[],requests=[];
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH || undefined,args:['--no-sandbox'],headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/qa-image.svg',r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="800" height="500" fill="#e9f0f3"/><rect x="240" y="145" width="320" height="220" rx="25" fill="#174d70"/><circle cx="400" cy="255" r="80" fill="#fff"/><circle cx="400" cy="255" r="50" fill="#476c80"/></svg>'}));
 await page.route('**/qa-video.mp4',r=>r.fulfill({status:404,body:'Intentional media failure'}));
 await page.route('**/api/**',async route=>{
  const req=route.request(), url=new URL(req.url()), path=url.pathname.replace('/api',''); requests.push(path);
  let data=[];
  if(path==='/auth/me') data=admin;
  else if(path==='/auth/login') data={accessToken:'qa-fixture',user:admin};
  else if(path==='/resources') data=[fixture,blocked];
  else if(path==='/laboratories') data=[{id:'lab-a',code:'LAB',name:'Phòng thực hành',isActive:true}];
  else if(path.endsWith('/media/config')) data={uploadConfigured:false,externalHosts:['upload.wikimedia.org']};
  else if(path.endsWith('/media')) data=fixture.media;
  else if(path.endsWith('/schedule')) data={bookings:[],maintenanceWindows:[]};
  else if(path.endsWith('/history')) data={timeline:[]};
  else if(path==='/resources/equipment-a') {if(req.method()==='PATCH'){patches.push(req.postDataJSON());data={...fixture,...req.postDataJSON()};}else data=fixture;}
  else if(path==='/resources/equipment-b') data=blocked;
  else if(path==='/dashboard') data={generatedAt:new Date().toISOString(),summary:{},resources:[],bookings:[]};
  return route.fulfill({contentType:'application/json',body:JSON.stringify(data)});
 });
 let checks=0;const check=(cond)=>{assert.ok(cond);checks++};
 await page.goto(base);
 await page.getByRole('button',{name:'Xem chi tiết: '+fixture.name}).click();
 await page.getByRole('heading',{name:'Hướng dẫn sử dụng',exact:true}).waitFor();
 check(await page.locator('#chi-tiet-tai-nguyen .lab-resource-gallery figure').count()===1);
 check(await page.locator('#chi-tiet-tai-nguyen video').count()===0);
 check((await page.locator('#chi-tiet-tai-nguyen').innerText()).includes('0:00'));
 check(!requests.some(p=>p==='/resources/equipment-a/media'));
 await page.locator('.lab-gallery-choices').getByRole('button',{name:/Video/}).click();
 await page.getByText('Bạn vẫn có thể xem thông tin và điều kiện sử dụng.').waitFor();checks++;
 await page.locator('.lab-gallery-choices').getByRole('button',{name:/Ảnh/}).click();
 check(await page.locator('#chi-tiet-tai-nguyen img').count()===1);
 await page.locator('#chi-tiet-tai-nguyen').screenshot({path:`${screenshots}/desktop.png`});
 for(const width of [375,768,1024,1440]){
  await page.setViewportSize({width,height:900});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 }
 await page.setViewportSize({width:375,height:900});await page.locator('#chi-tiet-tai-nguyen').screenshot({path:`${screenshots}/mobile.png`});
 await page.setViewportSize({width:1440,height:1000});
 check((await page.locator('.catalog-guest-booking').getAttribute('open'))===null);
 await page.locator('.catalog-guest-booking > summary').click();
 await page.locator('#guest-booking-purpose').fill('Mục đích kiểm thử');
 await page.locator('.catalog-guest-booking > summary').click();
 await page.locator('.catalog-guest-booking > summary').click();
 check(await page.locator('#guest-booking-purpose').inputValue()==='Mục đích kiểm thử');
 await page.locator('.public-language').getByRole('button',{name:'EN',exact:true}).click();
 await page.getByRole('heading',{name:'Usage guide',exact:true}).waitFor();
 check(await page.locator('#guest-booking-purpose').inputValue()==='Mục đích kiểm thử');
 await page.locator('.public-language').getByRole('button',{name:'VI',exact:true}).click();
 await page.getByRole('button',{name:'Xem chi tiết: '+blocked.name}).click();
 await page.getByText(/Khả năng sử dụng:.*Hạn chế đặt lịch/).waitFor();
 check(await page.locator('#chi-tiet-tai-nguyen .public-primary').isDisabled());
 check(await page.locator('#chi-tiet-tai-nguyen .guest-booking-panel').count()===0);
 await page.locator('input[type=email]').fill(admin.email);
 await page.locator('input[type=password]').first().fill('FixturePassword!');
 await page.getByRole('button',{name:/ĐĂNG NHẬP VÀO HỆ THỐNG/i}).click();
 await openWorkspace(page);
 check(await page.locator('.sidebar-2026').count()===1);
 await page.locator('[data-nav-id=admin_management]').click();
 await page.getByRole('button',{name:/Sửa CAM-01/}).waitFor();
 await page.getByRole('button',{name:/Sửa CAM-01/}).click();
 await page.locator('#resource-guide-steps').fill('Bước đã chỉnh sửa.\nGhi nhận kết quả.');
 await page.getByRole('button',{name:'Lưu thay đổi',exact:true}).click();
 await page.waitForFunction(()=>!document.getElementById('resource-guide-steps'));
 check(patches.length===1);check(patches[0].specs.resolution==='24 MP');check(patches[0].specs.usageGuide.steps.length===2);
 check(patches[0].specs.usageGuide.safetyNotes.includes('\n'));
 await page.getByRole('button',{name:/Xem CAM-01/}).click();
 await page.getByRole('dialog').waitFor();
 check(await page.getByRole('dialog').getByRole('heading',{name:'Hướng dẫn sử dụng',exact:true}).count()===1);
 await page.keyboard.press('Escape');check(await page.getByRole('dialog').count()===0);
 check(errors.length===0);
 console.log(JSON.stringify({checks,errors,patches:patches.length,viewportWidths:[375,768,1024,1440],type:'Isolated browser fixtures; not database or storage integration'}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
