import React from "react";
import { ArrowRight, Building2, CalendarDays, GraduationCap, ShieldAlert, Users, Wrench } from "lucide-react";
import { translate as t } from "../../../i18n.js";
import { EmptyState, GroupCards, PriorityTiles, QuickLink, SectionTitle } from "./HomeComponents";
import type { RoleHomeProps } from "./homeTypes";

const roles = ["STUDENT", "LECTURER", "LAB_STAFF", "ADMIN"];
const roleKeys: Record<string, string> = { STUDENT: "ui.student_1b487b2d", LECTURER: "ui.lecturer_948c8824", LAB_STAFF: "ui.lab_staff_38b791e1", ADMIN: "ui.administrator_d00831ec" };
export function AdminHome(props: RoleHomeProps) {
  const { users, bookings, incidents, dashboard, onNavigate } = props;
  const overdue = bookings.filter(row => row.status === "CHECKED_OUT" && new Date(row.endAt).getTime() < Date.now());
  const open = incidents.filter(row => !["resolved", "closed"].includes(row.status.toLowerCase()));
  return <><section className="home-role-banner home-admin-banner"><div><span className="workspace-overline">{t("ui.home.admin.eyebrow")}</span><h2>{t("ui.home.admin.title")}</h2><p>{t("ui.home.admin.description")}</p><div className="home-banner-actions"><button className="primary-button" onClick={() => onNavigate("admin_management")}><Building2 size={18} aria-hidden="true" />{t("ui.home.admin.manageResources")}<ArrowRight size={17} aria-hidden="true" /></button><button className="secondary-button" onClick={() => onNavigate("users")}><Users size={18} aria-hidden="true" />{t("ui.home.admin.manageUsers")}</button></div></div><div className="home-admin-totals"><div><Building2 size={20} aria-hidden="true" /><strong>{dashboard?.summary.totalResources ?? "—"}</strong><span>{t("ui.home.admin.resourceCount")}</span></div><div><Users size={20} aria-hidden="true" /><strong>{users.filter(row => row.isActive).length}</strong><span>{t("ui.home.admin.activeUsers")}</span></div></div></section>
    <PriorityTiles items={[
      { count: bookings.filter(row => row.status === "PENDING_APPROVAL").length, label: "ui.home.admin.pending", hint: "ui.home.admin.pendingHint", icon: CalendarDays, onClick: () => onNavigate("bookings", { filter: "PENDING_APPROVAL" }) },
      { count: overdue.length, label: "ui.home.admin.overdue", hint: "ui.home.admin.overdueHint", icon: Wrench, urgent: true, onClick: () => onNavigate("bookings", { filter: "CHECKED_OUT" }) },
      { count: open.length, label: "ui.home.admin.incidents", hint: "ui.home.admin.incidentsHint", icon: ShieldAlert, urgent: true, onClick: () => onNavigate("incidents") }
    ]} />
    <div className="home-content-split"><section className="home-panel"><SectionTitle eyebrow="ui.home.admin.peopleEyebrow" titleKey="ui.home.admin.peopleTitle" action="ui.home.admin.manageUsers" onAction={() => onNavigate("users")} /><div className="home-role-grid">{roles.map(role => <button className="home-role-card" key={role} onClick={() => onNavigate("users", { role })}><span className="home-icon-box">{role === "LECTURER" ? <GraduationCap size={21} aria-hidden="true" /> : <Users size={21} aria-hidden="true" />}</span><strong>{users.filter(row => row.role === role).length}</strong><span>{t(roleKeys[role])}</span><small>{t("ui.home.admin.roleHint")}</small><ArrowRight size={17} aria-hidden="true" /></button>)}</div><div className="home-context-note"><Users size={20} aria-hidden="true" /><p>{t("ui.home.admin.assignmentHint")}</p></div></section><aside className="home-panel"><SectionTitle titleKey="ui.home.admin.controlTitle" /><QuickLink icon={Building2} titleKey="ui.home.admin.classification" detail="ui.home.admin.classificationHint" onClick={() => onNavigate("admin_management", { classification: "UNRESOLVED" })} /><QuickLink icon={Wrench} titleKey="ui.home.admin.maintenance" detail="ui.home.admin.maintenanceHint" onClick={() => onNavigate("maintenance")} /><QuickLink icon={Users} titleKey="ui.home.admin.staff" detail="ui.home.admin.staffHint" onClick={() => onNavigate("users", { role: "LAB_STAFF" })} /></aside></div>
    <div className="home-content-split"><section className="home-panel"><SectionTitle titleKey="ui.home.admin.groups" action="ui.home.groups.manage" onAction={() => onNavigate("teaching")} /><GroupCards {...props} /></section><section className="home-panel"><SectionTitle titleKey="ui.home.admin.incidentTitle" action="ui.view_all_44aeb8cb" onAction={() => onNavigate("incidents")} />{open.length ? <div className="home-job-list">{open.slice(0, 3).map(row => <button key={row.id} onClick={() => onNavigate("incidents")}><ShieldAlert size={18} aria-hidden="true" /><span><strong>{row.title}</strong><small>{row.resource?.name}</small><span>{t(`ui.home.severity.${row.severity}`)}</span></span><ArrowRight size={16} aria-hidden="true" /></button>)}</div> : <EmptyState icon={ShieldAlert} titleKey="ui.home.admin.noIncidents" detail="ui.home.admin.noIncidentsHint" />}</section></div>
  </>;
}
