import React from "react";
import { ArrowRight, Bell, CalendarDays, CheckCircle2, Clock3, GraduationCap, MapPin, type LucideIcon } from "lucide-react";
import { translate as t, localizeNotification } from "../../../i18n.js";
import { BookingStatusBadge } from "../../BookingStatusBadge";
import { formatVietnamDateTime } from "../../../utils/timezone";
import type { BookingRecord } from "../../../types/booking";
import type { HomeNavigate, HomeNotice, RoleHomeProps } from "./homeTypes";

export function SectionTitle({ titleKey, action, onAction }: { eyebrow?: string; titleKey: string; action?: string; onAction?: () => void }) {
  return <div className="home-section-heading"><div><h2>{t(titleKey)}</h2></div>{action && <button className="home-text-button" onClick={onAction}>{t(action)}<ArrowRight size={16} aria-hidden="true" /></button>}</div>;
}
export function QuickLink({ icon: Icon, titleKey, detail, onClick }: { icon: LucideIcon; titleKey: string; detail: string; onClick: () => void }) {
  return <button className="home-quick-link" onClick={onClick}><span className="home-icon-box"><Icon size={21} aria-hidden="true" /></span><span><strong>{t(titleKey)}</strong><small>{t(detail)}</small></span><ArrowRight size={17} aria-hidden="true" /></button>;
}
export function PriorityTiles({ items, scopeKey = "ui.home.dataScope" }: { scopeKey?: string; items: { count: number; label: string; hint: string; icon: LucideIcon; urgent?: boolean; onClick: () => void }[] }) {
  return <section className="home-priorities"><div className="home-attention-grid">{items.map(({ count, label, hint, icon: Icon, urgent, onClick }) => <button className={`home-attention-card${urgent && count ? " is-urgent" : ""}`} key={label} onClick={onClick}><span className="home-priority-icon"><Icon size={18} aria-hidden="true" /></span><span className="home-priority-copy"><span className="home-priority-label">{t(label)}</span><small>{t(hint)}</small></span><strong className="home-priority-count">{count}</strong><ArrowRight size={16} aria-hidden="true" /></button>)}</div><p className="home-data-scope">{t(scopeKey)}</p></section>;
}
export function EmptyState({ titleKey, detail, action, onAction, icon: Icon = CalendarDays }: { titleKey: string; detail: string; action?: string; onAction?: () => void; icon?: LucideIcon }) {
  return <div className="home-empty"><span className="home-empty-icon"><Icon size={26} aria-hidden="true" /></span><h3>{t(titleKey)}</h3><p>{t(detail)}</p>{action && <button className="secondary-button" onClick={onAction}>{t(action)}<ArrowRight size={16} aria-hidden="true" /></button>}</div>;
}
export function BookingList({ rows, onNavigate, staff = false }: { rows: BookingRecord[]; onNavigate: HomeNavigate; staff?: boolean }) {
  return <div className="home-booking-list">{rows.map(row => <button className="home-booking-row" key={row.id} onClick={() => onNavigate("bookings", { booking: row.id })}><span className="home-icon-box"><CalendarDays size={20} aria-hidden="true" /></span><span className="home-booking-copy"><small>{row.resource?.code}</small><strong>{row.resource?.name || row.title}</strong><time dateTime={row.startAt}>{formatVietnamDateTime(row.startAt)}</time><span>{staff ? row.requestedBy?.fullName : row.title}</span></span><BookingStatusBadge status={row.status} /><ArrowRight size={17} aria-hidden="true" /></button>)}</div>;
}
export function NextBooking({ booking, onNavigate, onCalendar }: { booking?: BookingRecord; onNavigate: HomeNavigate; onCalendar: () => void }) {
  return <section className="home-next-ticket" aria-labelledby="home-next-title"><div className="home-ticket-top"><span className="workspace-overline">{t("ui.home.next.eyebrow")}</span><CalendarDays size={22} aria-hidden="true" /></div><h2 id="home-next-title">{t(booking?.status === "CHECKED_OUT" ? "ui.home.next.inUse" : "ui.home.next.title")}</h2>{booking ? <><BookingStatusBadge status={booking.status} /><h3>{booking.resource?.name || booking.title}</h3><p className="home-ticket-purpose">{booking.title}</p><dl className="home-ticket-details"><div><dt><Clock3 size={16} aria-hidden="true" />{t("ui.home.next.start")}</dt><dd><time dateTime={booking.startAt}>{formatVietnamDateTime(booking.startAt)}</time></dd></div><div><dt><Clock3 size={16} aria-hidden="true" />{t("ui.home.next.end")}</dt><dd><time dateTime={booking.endAt}>{formatVietnamDateTime(booking.endAt)}</time></dd></div>{booking.resource?.laboratory && <div><dt><MapPin size={16} aria-hidden="true" />{t("ui.home.next.location")}</dt><dd>{booking.resource.laboratory.name}</dd></div>}</dl><p className="home-ticket-note"><CheckCircle2 size={17} aria-hidden="true" />{t(booking.status === "CHECKED_OUT" ? "ui.home.next.returnHint" : "ui.home.next.handoverHint")}</p><button className="secondary-button" onClick={() => onNavigate("bookings", { booking: booking.id })}>{t("ui.home.next.open")}<ArrowRight size={16} aria-hidden="true" /></button></> : <EmptyState titleKey="ui.home.next.empty" detail="ui.home.next.emptyHint" action="ui.home.findSlot" onAction={onCalendar} />}</section>;
}
export function GroupCards({ groups, groupsLoading, groupsError, onRetryGroups, onNavigate, user }: Pick<RoleHomeProps, "groups" | "groupsLoading" | "groupsError" | "onRetryGroups" | "onNavigate" | "user">) {
  if (groupsLoading) return <p className="home-section-status" role="status">{t("ui.home.groups.loading")}</p>;
  if (groupsError) return <div className="home-section-error" role="alert"><p>{t("ui.home.groups.error")}</p><button className="secondary-button" onClick={onRetryGroups}>{t("ui.retry_c58d068c")}</button></div>;
  if (!groups.length) return <EmptyState icon={GraduationCap} titleKey="ui.home.groups.empty" detail={user.role === "ADMIN" ? "ui.home.groups.adminEmpty" : "ui.home.groups.emptyHint"} action={user.role === "ADMIN" ? "ui.home.groups.manage" : "ui.home.profile"} onAction={() => onNavigate(user.role === "ADMIN" ? "teaching" : "profile")} />;
  return <div className="home-group-grid">{groups.slice(0, 4).map(group => <button className="home-group-card" key={group.id} onClick={() => onNavigate("teaching", { group: group.id })}><span className="home-icon-box"><GraduationCap size={22} aria-hidden="true" /></span><span className="home-group-summary"><small>{group.code} · {group.term}</small><h3>{group.name}</h3><span>{group.lecturer.fullName}</span></span><span className="home-group-counts"><span>{t("ui.home.groups.members", { count: group._count.members })}</span><span>{t("ui.home.groups.activities", { count: group._count.activities })}</span></span><span className="home-group-cta">{t(user.role === "LECTURER" ? "ui.home.groups.review" : "ui.home.groups.open")}<ArrowRight size={16} aria-hidden="true" /></span></button>)}</div>;
}
export function Notices({ rows, onNavigate }: { rows: HomeNotice[]; onNavigate: HomeNavigate }) {
  const recent = [...rows].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 3).map(row => localizeNotification(row) as HomeNotice);
  return <section className="home-panel home-notices"><SectionTitle titleKey="ui.home.notices" action="ui.view_all_44aeb8cb" onAction={() => onNavigate("escalations")} />{recent.length ? <div className="home-notice-list">{recent.map(row => <button key={row.id} className="home-notice" onClick={() => onNavigate("escalations")}><Bell size={18} aria-hidden="true" /><span><strong>{row.title}{!row.readAt && <span className="home-unread">{t("ui.new_0c09ff84")}</span>}</strong><span>{row.message}</span><time dateTime={row.createdAt}>{formatVietnamDateTime(row.createdAt)}</time></span><ArrowRight size={16} aria-hidden="true" /></button>)}</div> : <p className="home-notices-empty">{t("ui.no_notifications_yet_booking_outcomes_7656d6fd")}</p>}</section>;
}
