import React, { useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, DoorOpen, FlaskConical, GraduationCap, Microscope, Search, ShieldCheck } from "lucide-react";
import { translate as t } from "../../../i18n.js";
import { EmptyState, GroupCards, NextBooking, PriorityTiles, QuickLink, SectionTitle } from "./HomeComponents";
import { ownBookings, upcomingBookings } from "./homeSelectors";
import type { RoleHomeProps } from "./homeTypes";

const categories = [{ value: "ROOM", label: "ui.home.category.rooms", icon: DoorOpen }, { value: "EQUIPMENT", label: "ui.home.category.equipment", icon: Microscope }, { value: "EXPERIMENT_KIT", label: "ui.home.category.kits", icon: FlaskConical }];

export function StudentHome(props: RoleHomeProps) {
  const { onNavigate, onSearch, onCalendar, resources } = props;
  const [query, setQuery] = useState(""), [category, setCategory] = useState("");
  const rows = ownBookings(props), upcoming = upcomingBookings(rows);
  const checkedOut = rows.filter(row => row.status === "CHECKED_OUT"), pending = rows.filter(row => row.status === "PENDING_APPROVAL");
  const overdue = checkedOut.filter(row => new Date(row.endAt).getTime() < Date.now());
  const catalogue = resources.filter(row => row.bookingState === "bookable" && categories.some(item => item.value === row.category));
  const representatives = categories.map(item => catalogue.find(row => row.category === item.value)).filter(Boolean);
  const featured = [...representatives, ...catalogue.filter(row => !representatives.some(item => item.id === row.id))].slice(0, 3);
  return <>
    <div className="home-student-lead"><section className="home-finder"><span className="workspace-overline">{t("ui.home.student.eyebrow")}</span><h2>{t("ui.home.student.title")}</h2><p>{t("ui.home.student.description")}</p><form className="home-finder-form" onSubmit={event => { event.preventDefault(); onSearch(query.trim(), category); }}><div><Search size={21} aria-hidden="true" /><label className="sr-only" htmlFor="home-resource-query">{t("ui.find_a_resource_2d5d3f8f")}</label><input id="home-resource-query" type="search" maxLength={120} value={query} onChange={event => setQuery(event.target.value)} placeholder={t("ui.home.student.searchPlaceholder")} /></div><label className="sr-only" htmlFor="home-resource-category">{t("ui.home.category.label")}</label><select id="home-resource-category" value={category} onChange={event => setCategory(event.target.value)}><option value="">{t("ui.home.category.all")}</option>{categories.map(item => <option key={item.value} value={item.value}>{t(item.label)}</option>)}</select><button className="primary-button" type="submit">{t("ui.home.student.search")}<ArrowRight size={18} aria-hidden="true" /></button></form><div className="home-category-shortcuts">{categories.map(({ value, label, icon: Icon }) => <button key={value} onClick={() => onSearch("", value)}><Icon size={19} aria-hidden="true" />{t(label)}<ArrowRight size={15} aria-hidden="true" /></button>)}</div><div className="home-finder-foot"><ShieldCheck size={18} aria-hidden="true" /><span>{t("ui.home.student.calendarHint")}</span></div></section><NextBooking booking={overdue[0] || upcoming[0]} onNavigate={onNavigate} onCalendar={() => onCalendar()} /></div>
    <PriorityTiles items={[
      { count: pending.length, label: "ui.home.student.pending", hint: "ui.home.student.pendingHint", icon: CalendarDays, onClick: () => onNavigate("bookings", { filter: "PENDING_APPROVAL" }) },
      { count: checkedOut.length, label: "ui.home.student.inUse", hint: "ui.home.student.returnHint", icon: Clock3, urgent: overdue.length > 0, onClick: () => onNavigate("bookings", { filter: "CHECKED_OUT" }) },
      { count: props.incidents.filter(row => !["resolved", "closed"].includes(row.status.toLowerCase())).length, label: "ui.home.student.incidents", hint: "ui.home.student.incidentHint", icon: CheckCircle2, onClick: () => onNavigate("incidents") }
    ]} />
    <div className="home-content-split"><section className="home-panel"><SectionTitle eyebrow="ui.home.student.catalogEyebrow" titleKey="ui.home.student.catalogTitle" action="ui.home.student.browseAll" onAction={() => onSearch("")} />{featured.length ? <div className="home-resource-grid">{featured.map(row => { const Icon = row.category === "ROOM" ? DoorOpen : row.category === "EXPERIMENT_KIT" ? FlaskConical : Microscope; return <article className="home-resource-card" key={row.id}><div className={`home-resource-cover category-${row.category}`}><Icon size={40} strokeWidth={1.3} aria-hidden="true" /><span>{row.code}</span></div><div className="home-resource-body"><small>{t(`enum.category.${row.category}`)}</small><h3>{row.name}</h3><p>{row.laboratory?.name || t("ui.home.resource.noLab")}</p><span className="home-resource-state">{t(`enum.operational.${row.operationalStatus}`)}</span><button className="home-text-button" onClick={() => onCalendar(row.id)}>{t("ui.home.resource.calendar")}<ArrowRight size={16} aria-hidden="true" /></button></div></article>; })}</div> : <EmptyState titleKey="ui.home.resource.empty" detail="ui.home.resource.emptyHint" action="ui.home.student.browseAll" onAction={() => onSearch("")} />}<p className="home-section-footnote">{t("ui.home.resource.availabilityHint")}</p></section><aside className="home-panel home-prepare"><SectionTitle titleKey="ui.home.student.prepare" /><QuickLink icon={ShieldCheck} titleKey="ui.home.profile" detail="ui.home.profileHint" onClick={() => onNavigate("profile")} /><QuickLink icon={GraduationCap} titleKey="ui.home.student.groups" detail="ui.home.student.groupsHint" onClick={() => onNavigate("teaching")} /><div className="home-workflow-guide"><span className="workspace-overline">{t("ui.home.student.stepsTitle")}</span>{["find", "request", "receive"].map((step, index) => <div key={step}><span>{index + 1}</span><p><strong>{t(`ui.home.steps.${step}`)}</strong><small>{t(`ui.home.steps.${step}Hint`)}</small></p></div>)}</div></aside></div>
    <section className="home-panel"><SectionTitle titleKey="ui.home.student.myGroups" action="ui.home.groups.manage" onAction={() => onNavigate("teaching")} /><GroupCards {...props} /></section>
  </>;
}
