import React, { useCallback, useEffect, useState } from 'react';
import { apiRequest } from '../api.js';
import { useLocale } from '../providers/LocaleProvider';
import { CANONICAL_BOOKING_STATUS_LABELS } from '../constants.js';
import { formatVietnamDateTime } from '../utils/timezone';
import '../styles/lab-workspace.css';

type Row = Record<string, any>;
type Props = { locale: string; user: { id: string; role: string }; bookings?: Row[]; maintenance?: Row[] };
const send = (path: string, body: Row, method = 'POST') => apiRequest(`/lab-workspace${path}`, { method, body: JSON.stringify(body) });
const message = (error: unknown) => error instanceof Error ? error.message : 'Request failed';

export function StockPage({ locale, user, maintenance = [] }: Props) {
  const t = (vi: string, en: string) => locale === 'en' ? en : vi;
  const [rows, setRows] = useState<Row[]>([]), [history, setHistory] = useState<Row[]>([]);
  const [selected, setSelected] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [revision, setRevision] = useState(0);
  const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  const [kind, setKind] = useState('RECEIPT');
  const load = useCallback(() => { setLoading(true); setError(''); return apiRequest('/lab-workspace/stock').then(setRows).catch((e: unknown) => setError(message(e))).finally(() => setLoading(false)); }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { let active = true; setHistory([]); if (selected) apiRequest(`/lab-workspace/stock/${selected}`).then((data: Row[]) => { if (active) setHistory(data); }).catch((e: unknown) => { if (active) setError(message(e)); }); return () => { active = false; }; }, [selected, revision]);
  const item = rows.find(row => row.id === selected);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return;
    const form = event.currentTarget, values = new FormData(form);
    setBusy(true); setError(''); setNotice('');
    try {
      await send('/stock', { id: requestId, resourceId: selected, kind, quantity: Number(values.get('quantity')), unit: item?.stockItem?.unit || String(values.get('unit')).trim(), reason: values.get('reason'), reference: values.get('reference'), ...(values.get('maintenanceId') ? { maintenanceId: values.get('maintenanceId') } : {}) });
      setRequestId(crypto.randomUUID()); form.reset(); setRevision(value => value + 1); await load(); setNotice(t('Đã ghi sổ kho. Phiếu được lưu cùng lịch sử người thực hiện.', 'Movement recorded with an immutable operator history.'));
    } catch (e) { setError(message(e)); } finally { setBusy(false); }
  }
  return <section className="lab-workspace" aria-labelledby="stock-title">
    <header className="lab-page-heading"><div><h1 id="stock-title">{t('Kho vật tư', 'Materials inventory')}</h1><p>{t('Nhập theo chứng từ. Xuất theo mục đích. Đối chiếu tồn thực tế trước khi điều chỉnh.', 'Receive against a reference, issue for a purpose, and count physical stock before adjusting.')}</p></div><button className="secondary-button" onClick={load} disabled={busy || loading}>{t('Tải lại', 'Refresh')}</button></header>
    {error && <p className="alert danger" role="alert">{error}</p>}{notice && <p className="alert success" role="status">{notice}</p>}
    {loading ? <p role="status">{t('Đang tải kho…', 'Loading inventory…')}</p> : <div className="lab-split">
      <div className="lab-register"><h2>{t('Danh mục vật tư', 'Material register')}</h2>{!rows.length && <p>{t('Chưa có vật tư trong LAB được phân công. Tạo tài nguyên thuộc nhóm Vật tư trước.', 'No materials in your assigned laboratories. Create a MATERIAL resource first.')}</p>}
        {rows.map(row => <button className="lab-register-row" key={row.id} aria-pressed={selected === row.id} disabled={busy} onClick={() => { setSelected(row.id); setKind('RECEIPT'); setError(''); setNotice(''); setRequestId(crypto.randomUUID()); }}><span><small>{row.code}</small><strong>{row.name}</strong></span><span>{row.stockItem ? `${row.stockItem.balance} ${row.stockItem.unit}` : t('Chưa kiểm kê', 'Not counted')}</span></button>)}
      </div>
      <div>{item ? <><form key={selected} className="lab-form" onSubmit={submit} onChange={() => setRequestId(crypto.randomUUID())}><h2>{item.name}</h2><p>{item.stockItem ? `${t('Tồn sổ', 'Recorded balance')}: ${item.stockItem.balance} ${item.stockItem.unit}` : t('Chưa có số tồn. Phiếu nhập đầu tiên phải dựa trên kiểm kê hoặc chứng từ thật.', 'No opening balance. Record the first receipt from a verified count or receipt.')}</p>
        <fieldset disabled={busy}><label>{t('Loại phiếu', 'Movement')}<select value={kind} onChange={e => { setKind(e.target.value); setRequestId(crypto.randomUUID()); }}><option value="RECEIPT">{t('Nhập kho', 'Receipt')}</option><option value="ISSUE" disabled={!item.stockItem}>{t('Xuất kho', 'Issue')}</option>{user.role === 'ADMIN' && <option value="ADJUSTMENT" disabled={!item.stockItem}>{t('Điều chỉnh kiểm kê', 'Count adjustment')}</option>}</select></label>
        <div className="lab-fields"><label>{t('Số lượng', 'Quantity')}<input name="quantity" type="number" step="1" min={kind === 'ADJUSTMENT' ? -1000000 : 1} max="1000000" required /></label><label>{t('Đơn vị tính', 'Unit')}<input name="unit" defaultValue={item.stockItem?.unit || ''} readOnly={Boolean(item.stockItem)} required maxLength={30} placeholder={t('cái, hộp, cuộn…', 'piece, box, roll…')} /></label></div>
        {kind === 'ADJUSTMENT' && <p className="lab-help">{t('Nhập chênh lệch có dấu: -2 để giảm 2, +3 để tăng 3. Không nhập tổng tồn mới.', 'Enter a signed difference: -2 removes 2; +3 adds 3. Do not enter the new total.')}</p>}
        <label>{t('Mã chứng từ / biên bản', 'Receipt or count reference')}<input name="reference" required minLength={2} maxLength={120} /></label><label>{t('Lý do và người / bộ phận nhận', 'Reason and recipient or department')}<textarea name="reason" required minLength={5} maxLength={500} rows={3} /></label>
        {kind === 'ISSUE' && <label>{t('Cấp cho công việc bảo trì', 'Issue for maintenance')}<select name="maintenanceId"><option value="">{t('Không gắn bảo trì', 'Not related to maintenance')}</option>{maintenance.filter(job => ['scheduled', 'in_progress'].includes(job.status) && job.resource?.laboratoryId === item.laboratoryId).map(job => <option key={job.id} value={job.id}>{job.title}</option>)}</select></label>}
        <button className="primary-button" type="submit">{busy ? t('Đang ghi sổ…', 'Recording…') : t('Ghi phiếu kho', 'Record movement')}</button></fieldset></form>
        <section className="lab-history"><h2>{t('Sổ giao dịch gần nhất', 'Recent movement ledger')}</h2><p className="lab-help">{t('Tối đa 100 phiếu gần nhất. Sai sót được sửa bằng phiếu điều chỉnh, không xóa lịch sử.', 'Latest 100 entries. Correct errors with an adjustment; historical movements are retained.')}</p>{history.map(row => <article className="lab-ledger-row" key={row.id}><div><strong>{row.delta > 0 ? '+' : ''}{row.delta} {item.stockItem?.unit}</strong><span>{row.reference} · {formatVietnamDateTime(row.createdAt)}</span></div><p>{row.reason}</p><small>{row.actor.fullName} · {t('Tồn sau phiếu', 'Balance after')}: {row.balanceAfter}{row.maintenance && ` · ${row.maintenance.title}`}</small></article>)}</section></> : <p className="lab-empty">{t('Chọn vật tư để kiểm tra tồn và lập phiếu.', 'Select a material to inspect its balance and record a movement.')}</p>}</div>
    </div>}
  </section>;
}

export function TeachingPage({ locale, user, bookings = [] }: Props) {
  const { tr } = useLocale();
  const t = (vi: string, en: string) => locale === 'en' ? en : vi;
  const [groups, setGroups] = useState<Row[]>([]), [detail, setDetail] = useState<Row | null>(null);
  const [selected, setSelected] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [revision, setRevision] = useState(0);
  const manager = user.role !== 'STUDENT';
  useEffect(() => { let active = true; setLoading(true); apiRequest('/lab-workspace/groups').then((data: Row[]) => { if (active) setGroups(data); }).catch((e: unknown) => { if (active) setError(message(e)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [revision]);
  useEffect(() => { let active = true; setDetail(null); if (selected) apiRequest(`/lab-workspace/groups/${selected}`).then((data: Row) => { if (active) setDetail(data); }).catch((e: unknown) => { if (active) setError(message(e)); }); return () => { active = false; }; }, [selected, revision]);
  async function submit(event: React.FormEvent<HTMLFormElement>, path: string, method = 'POST') {
    event.preventDefault(); if (busy) return;
    const form = event.currentTarget;
    setBusy(true); setError(''); setNotice('');
    try { await send(path, Object.fromEntries(new FormData(form)), method); form.reset(); setRevision(value => value + 1); setNotice(t('Đã lưu thay đổi.', 'Changes saved.')); } catch (e) { setError(message(e)); } finally { setBusy(false); }
  }
  return <section className="lab-workspace" aria-labelledby="teaching-title"><header className="lab-page-heading"><div><h1 id="teaching-title">{t('Lớp và nhóm học phần', 'Classes and course groups')}</h1><p>{t('Theo dõi mục tiêu thực hành và phản hồi học thuật. Cán bộ LAB vẫn duyệt lịch và chịu trách nhiệm bàn giao.', 'Track practical learning goals and academic feedback. LAB staff still approve resource bookings and manage handover.')}</p></div></header>
    {error && <p className="alert danger" role="alert">{error}</p>}{notice && <p className="alert success" role="status">{notice}</p>}
    {user.role === 'ADMIN' && <details className="lab-disclosure"><summary>{t('Tạo lớp và phân công giảng viên', 'Create a group and assign a lecturer')}</summary><form className="lab-form" onSubmit={event => void submit(event, '/groups')}><fieldset disabled={busy}><div className="lab-fields"><label>{t('Mã lớp', 'Group code')}<input name="code" required minLength={2} maxLength={40} /></label><label>{t('Học kỳ', 'Term')}<input name="term" required minLength={2} maxLength={80} /></label></div><label>{t('Tên lớp / học phần', 'Class or course name')}<input name="name" required minLength={3} maxLength={160} /></label><label>{t('Email giảng viên đã có tài khoản', 'Existing lecturer account email')}<input name="lecturerEmail" type="email" required /></label><button className="primary-button">{t('Tạo lớp', 'Create group')}</button></fieldset></form></details>}
    {loading ? <p role="status">{t('Đang tải…', 'Loading…')}</p> : <div className="lab-split"><div className="lab-register"><h2>{t('Nhóm được phân công', 'Assigned groups')}</h2>{!groups.length && <p className="lab-empty">{t('Chưa có nhóm được phân công. Liên hệ quản trị viên hoặc giảng viên phụ trách.', 'No assigned groups. Contact your administrator or course lecturer.')}</p>}{groups.map(group => <button className="lab-register-row" disabled={busy} key={group.id} aria-pressed={selected === group.id} onClick={() => { setSelected(group.id); setError(''); }}><span><small>{group.code} · {group.term}</small><strong>{group.name}</strong><small>{group.lecturer.fullName}</small></span></button>)}</div>
    <div>{!detail ? <p className="lab-empty">{t('Chọn nhóm để xem hoạt động.', 'Select a group to view its activities.')}</p> : <><h2>{detail.name}</h2>{manager && <><details className="lab-disclosure"><summary>{t('Danh sách và thêm sinh viên', 'Members and student enrollment')} ({detail.members.length})</summary><ul>{detail.members.map((member: Row) => <li key={member.userId}>{member.user.fullName}</li>)}</ul><form className="lab-form" onSubmit={event => void submit(event, `/groups/${selected}/members`)}><fieldset disabled={busy}><label>{t('Email sinh viên đã có tài khoản', 'Existing student account email')}<input name="email" type="email" required /></label><button className="secondary-button">{t('Thêm vào nhóm', 'Add to group')}</button></fieldset></form></details></>}
    {!manager && <form className="lab-form" onSubmit={event => void submit(event, `/groups/${selected}/activities`)}><h3>{t('Gửi hoạt động thực hành', 'Submit a practical activity')}</h3><fieldset disabled={busy}><label>{t('Lịch đặt của bạn', 'Your booking')}<select name="bookingId" required><option value="">{t('Chọn lịch đặt', 'Select a booking')}</option>{bookings.filter(row => row.requestedById === user.id && !['REJECTED', 'CANCELLED'].includes(row.status) && !detail.activities.some((a: Row) => a.bookingId === row.id)).map(row => <option value={row.id} key={row.id}>{row.title} · {formatVietnamDateTime(row.startAt)}</option>)}</select></label><label>{t('Mục tiêu thực hành', 'Learning objective')}<textarea name="learningGoal" required minLength={10} maxLength={1000} rows={3} /></label><button className="primary-button">{t('Gửi giảng viên', 'Submit to lecturer')}</button></fieldset></form>}
    <section className="lab-history"><h3>{t('Hoạt động đã gửi', 'Submitted activities')}</h3>{!detail.activities.length && <p>{t('Chưa có hoạt động nào được gửi.', 'No submitted activities.')}</p>}{detail.activities.map((activity: Row) => <article className="lab-ledger-row" key={activity.id}><strong>{activity.booking.requestedBy.fullName} · {activity.booking.resource.name}</strong><p>{activity.learningGoal}</p><small>{formatVietnamDateTime(activity.booking.startAt)} · {tr(CANONICAL_BOOKING_STATUS_LABELS[activity.booking.status] || activity.booking.status)}</small><p>{activity.decision === 'SUBMITTED' ? t('Chờ nhận xét', 'Awaiting review') : activity.decision === 'ENDORSED' ? t('Đã xác nhận mục tiêu', 'Learning goal endorsed') : t('Cần bổ sung', 'Changes requested')}</p>{activity.feedback && <blockquote>{activity.feedback}</blockquote>}{!manager && activity.decision === 'CHANGES_REQUESTED' && <form className="lab-form" onSubmit={event => void submit(event, `/groups/${selected}/activities/${activity.id}/revision`, 'PATCH')}><fieldset disabled={busy}><label>{t('Bổ sung mục tiêu theo nhận xét', 'Revise your learning goal')}<textarea name="learningGoal" required minLength={10} maxLength={1000} defaultValue={activity.learningGoal} rows={3} /></label><button className="primary-button">{t('Gửi lại giảng viên', 'Resubmit for review')}</button></fieldset></form>}{manager && <form className="lab-form" onSubmit={event => void submit(event, `/groups/${selected}/activities/${activity.id}`, 'PATCH')}><fieldset disabled={busy}><label>{t('Nhận xét', 'Feedback')}<textarea name="feedback" required minLength={5} maxLength={1000} rows={2} defaultValue={activity.feedback || ''} /></label><label>{t('Kết quả học thuật', 'Academic review')}<select name="decision" defaultValue={activity.decision === 'CHANGES_REQUESTED' ? 'CHANGES_REQUESTED' : 'ENDORSED'}><option value="ENDORSED">{t('Xác nhận mục tiêu', 'Endorse learning goal')}</option><option value="CHANGES_REQUESTED">{t('Yêu cầu bổ sung', 'Request changes')}</option></select></label><button className="secondary-button">{t('Lưu nhận xét', 'Save feedback')}</button></fieldset></form>}</article>)}</section></>}</div></div>}
  </section>;
}
