import React, { useState } from 'react';
import { apiRequest } from '../api.js';
import { formatVietnamDateTime, toVietnamDateString, toVietnamTimeString, vietnamTimeToIso } from '../utils/timezone';
import '../styles/lab-workspace.css';
type Row = Record<string, any>;
export function MaintenancePage({ locale, resources, maintenance, onChanged, onBookings }: { locale: string; resources: Row[]; maintenance: Row[]; onChanged: () => void; onBookings: () => void }) {
  const t = (vi: string, en: string) => locale === 'en' ? en : vi;
  const [editing, setEditing] = useState<Row | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [conflicts, setConflicts] = useState<Row[] | null>(null), [filter, setFilter] = useState('open');
  const [notice, setNotice] = useState('');
  const statusLabel = (status: string) => ({ scheduled: t('Đã lên lịch','Scheduled'), in_progress: t('Đang thực hiện','In progress'), completed: t('Hoàn thành','Completed'), cancelled: t('Đã hủy','Cancelled') } as Record<string,string>)[status] || status;
  const local = (iso: string) => `${toVietnamDateString(iso)}T${toVietnamTimeString(iso)}`;
  const parse = (value: FormDataEntryValue | null) => { const [date,time] = String(value || '').split('T'); return vietnamTimeToIso(date, time); };
  const payload = (form: HTMLFormElement) => { const values = new FormData(form); return { resourceId: values.get('resourceId'), title: values.get('title'), kind: values.get('kind'), startAt: parse(values.get('startAt')), endAt: parse(values.get('endAt')), notes: String(values.get('notes') || '').trim(), ...(editing?.id ? { changeReason: values.get('changeReason') } : { status: 'scheduled' }) }; };
  async function check(form: HTMLFormElement) {
    if (!form.reportValidity()) return;
    setBusy(true); setError(''); setConflicts(null);
    try { const data = payload(form); const query = new URLSearchParams({resourceId: String(data.resourceId), startAt: data.startAt, endAt: data.endAt}); const result = await apiRequest(`/maintenance/impact?${query}`); setConflicts(result.conflicts); } catch (e) { setError(e instanceof Error ? e.message : 'Request failed'); } finally { setBusy(false); }
  }
  async function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return; const data = payload(event.currentTarget); setBusy(true); setError(''); setNotice('');
    try { await apiRequest(editing?.id ? `/maintenance/${editing.id}` : '/maintenance', { method: editing?.id ? 'PATCH' : 'POST', body: JSON.stringify(data) }); setEditing(null); setConflicts(null); onChanged(); setNotice(t('Đã lưu lịch bảo trì sau khi kiểm tra lại xung đột.', 'Maintenance saved after rechecking conflicts.')); } catch (e: any) { setError(e.message); if (e.details?.conflicts) setConflicts(e.details.conflicts); } finally { setBusy(false); }
  }
  async function transition(event: React.FormEvent<HTMLFormElement>, row: Row) {
    event.preventDefault(); if (busy) return; const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); setBusy(true); setError('');
    try { await apiRequest(`/maintenance/${row.id}`, { method: 'PATCH', body: JSON.stringify(data) }); onChanged(); setNotice(t('Đã cập nhật công việc. Kiểm tra trạng thái vật lý riêng trước khi cho sử dụng lại.', 'Job updated. Inspect and update the physical resource state separately before reuse.')); } catch (e: any) { setError(e.message); } finally { setBusy(false); }
  }
  const visibleJobs = maintenance.filter(row => filter === 'all' || ['scheduled','in_progress'].includes(row.status));
  return <section className="lab-workspace"><header className="lab-page-heading"><div><h1>{t('Bảo trì và hiệu chuẩn','Maintenance and calibration')}</h1><p>{t('Lập lịch dừng thiết bị, kiểm tra lịch bị ảnh hưởng và ghi nhận công việc. Hoàn thành bảo trì không tự xác nhận thiết bị an toàn.', 'Plan equipment downtime, review affected bookings and record work. Completing a job does not certify equipment safety.')}</p></div><button className="primary-button" disabled={busy} onClick={() => { setEditing({}); setConflicts(null); setError(''); }}>{t('Lập lịch bảo trì','Schedule maintenance')}</button></header>
    {error && <p className="alert danger" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}
    {editing && <form key={editing.id || "new"} className="lab-form" onSubmit={save} onChange={() => setConflicts(null)}><h2>{editing.id ? t('Chuyển lịch bảo trì','Reschedule maintenance') : t('Công việc mới','New maintenance job')}</h2><fieldset disabled={busy}>
      <label>{t('Tài nguyên','Resource')}<select name="resourceId" required defaultValue={editing.resourceId || ''}><option value="">{t('Chọn tài nguyên','Select a resource')}</option>{resources.map(row => <option value={row.id} key={row.id}>{row.code} · {row.name}</option>)}</select></label>
      <div className="lab-fields"><label>{t('Tên công việc','Job title')}<input name="title" required minLength={3} maxLength={255} defaultValue={editing.title || ''}/></label><label>{t('Loại công việc','Job type')}<select name="kind" defaultValue={editing.kind || 'maintenance'}><option value="maintenance">{t('Bảo trì','Maintenance')}</option><option value="calibration">{t('Hiệu chuẩn','Calibration')}</option></select></label></div>
      <div className="lab-fields"><label>{t('Bắt đầu (UTC+07:00)','Start (UTC+07:00)')}<input type="datetime-local" name="startAt" required defaultValue={editing.startAt ? local(editing.startAt) : ''} /></label><label>{t('Kết thúc (UTC+07:00)','End (UTC+07:00)')}<input type="datetime-local" name="endAt" required defaultValue={editing.endAt ? local(editing.endAt) : ''} /></label></div>
      <label>{t('Ghi chú công việc','Work notes')}<textarea name="notes" maxLength={2000} rows={3} defaultValue={editing.notes || ''} /></label>{editing.id && <label>{t('Lý do chuyển lịch','Reason for rescheduling')}<input name="changeReason" required minLength={5} maxLength={500} /></label>}
      <div className="lab-inline-actions"><button type="button" className="secondary-button" onClick={event => { const form = event.currentTarget.form; if (form) void check(form); }}>{t('Kiểm tra lịch bị ảnh hưởng','Check affected bookings')}</button><button className="primary-button" disabled={conflicts === null || conflicts.length > 0}>{t('Lưu lịch bảo trì','Save maintenance')}</button><button type="button" className="secondary-button" onClick={() => setEditing(null)}>{t('Đóng','Close')}</button></div>
    </fieldset>{conflicts !== null && <div role="status"><h3>{conflicts.length ? t('Có lịch đặt trùng','Conflicting bookings') : t('Không có lịch đặt trùng ở lần kiểm tra này','No booking conflicts at this check')}</h3>{conflicts.map(row => <p key={row.id}>{row.title || row.id} · {formatVietnamDateTime(row.startAt)} — {formatVietnamDateTime(row.endAt)}</p>)}{conflicts.length > 0 && <><p>{t('Chọn khung bảo trì khác, hoặc phối hợp với người đặt để xử lý lịch bị ảnh hưởng. Không tự chuyển lịch của người dùng.', 'Choose another maintenance window or coordinate affected bookings with their owners. User bookings are not moved automatically.')}</p><button type="button" className="secondary-button" onClick={onBookings}>{t('Mở lịch đặt để phối hợp','Open bookings')}</button></>}</div>}</form>}
    <label>{t('Hiển thị công việc','Show jobs')} <select value={filter} onChange={e => setFilter(e.target.value)}><option value="open">{t('Chưa hoàn thành','Open')}</option><option value="all">{t('Tất cả','All')}</option></select></label>
    {visibleJobs.map(row => <article className="lab-ledger-row" key={row.id}><div><strong>{row.title}</strong><span>{statusLabel(row.status)}</span></div><p>{row.resource?.code} · {row.resource?.name}</p><p>{formatVietnamDateTime(row.startAt)} — {formatVietnamDateTime(row.endAt)}</p>{row.notes && <p>{row.notes}</p>}{['scheduled','in_progress'].includes(row.status) && <><button className="secondary-button" disabled={busy} onClick={() => { setEditing(row); setConflicts(null); window.scrollTo({top:0,behavior:'auto'}); }}>{t('Chuyển lịch / sửa công việc','Reschedule / edit job')}</button><details className="lab-disclosure"><summary>{t('Ghi nhận tiến độ hoặc hủy','Record progress or cancellation')}</summary><form className="lab-form" onSubmit={event => void transition(event,row)}><fieldset disabled={busy}><label>{t('Trạng thái mới','New status')}<select name="status">{row.status === 'scheduled' ? <option value="in_progress">{t('Bắt đầu thực hiện','Start work')}</option> : <option value="completed">{t('Hoàn thành công việc','Complete job')}</option>}<option value="cancelled">{t('Hủy công việc','Cancel job')}</option></select></label><label>{t('Kết quả / lý do','Outcome / reason')}<textarea name="changeReason" required minLength={5} maxLength={500}/></label><button className="primary-button">{t('Lưu tiến độ','Save progress')}</button></fieldset></form></details></>}</article>)}
    {!visibleJobs.length && <div className="lab-empty"><p>{filter === 'open' ? t('Không có công việc bảo trì chưa hoàn thành.', 'No open maintenance jobs.') : t('Chưa có lịch bảo trì trong phạm vi của bạn.', 'No maintenance jobs within your scope.')}</p>{filter === 'open' && maintenance.length > 0 && <button className="secondary-button" onClick={() => setFilter('all')}>{t('Xem tất cả công việc', 'View all jobs')}</button>}</div>}
  </section>;
}
