import React from "react";
import { ArrowRight, Bell, CalendarDays, CheckCircle2, Clock3, GraduationCap, Package, Search, ShieldAlert, Wrench } from "lucide-react";
import { formatVietnamDateTime } from "../utils/timezone";
import type { BookingRecord } from "../types/booking";
import "../styles/lab-workspace.css";
import "../styles/workspace-home.css";

interface Props {
  user: { id: string; fullName: string; role: string }; locale?: string; bookings: BookingRecord[];
  notifications: { id: string; title: string; message: string; readAt?: string; createdAt: string }[];
  incidents?: { status: string }[]; trainings?: unknown; loading: boolean; error: string;
  onNavigate: (tab: string) => void; onSearch: (query: string) => void; onRetry: () => void;
}
export function WorkspaceHome({ user, locale = "vi", bookings, notifications, incidents = [], loading, error, onNavigate, onSearch, onRetry }: Props) {
  const t = (vi: string, en: string) => locale === "en" ? en : vi;
  const staff = ["ADMIN", "LAB_STAFF"].includes(user.role);
  const rows = staff ? bookings : bookings.filter(row => row.requestedById === user.id);
  const now = Date.now();
  const pending = rows.filter(row => row.status === "PENDING_APPROVAL");
  const due = rows.filter(row => row.status === "CHECKED_OUT");
  const overdue = due.filter(row => new Date(row.endAt).getTime() < now);
  const inspection = rows.filter(row => row.status === "RETURNED");
  const open = incidents.filter(row => !["resolved", "closed"].includes(row.status.toLowerCase()));
  const upcoming = rows.filter(row => ["CONFIRMED", "CHECKED_OUT"].includes(row.status) && new Date(row.endAt).getTime() > now).sort((a, b) => a.startAt.localeCompare(b.startAt));
  const recent = [...notifications].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 3);
  const roleLabels: Record<string, string> = { ADMIN: t("Quản trị viên", "Administrator"), LAB_STAFF: t("Cán bộ LAB", "LAB staff"), LECTURER: t("Giảng viên", "Lecturer"), STUDENT: t("Sinh viên", "Student") };
  const attention = [
    { count: overdue.length, label: t("Quá hạn trả", "Overdue returns"), hint: t("Liên hệ và ghi nhận hoàn trả", "Coordinate and record returns"), tab: "bookings", icon: Clock3, tone: "danger" },
    { count: pending.length, label: t("Chờ phê duyệt", "Pending approval"), hint: staff ? t("Kiểm tra yêu cầu trước khi duyệt", "Review requests before approval") : t("Theo dõi kết quả từ cán bộ LAB", "Await the LAB approval outcome"), tab: "bookings", icon: CalendarDays, tone: "warning" },
    { count: staff ? inspection.length : due.length, label: staff ? t("Chờ kiểm tra sau trả", "Awaiting inspection") : t("Đang sử dụng", "Currently in use"), hint: staff ? t("Ghi tình trạng và hoàn tất bàn giao", "Record condition and complete handover") : t("Chuẩn bị hoàn trả đúng hạn", "Prepare to return on time"), tab: "bookings", icon: Package, tone: "neutral" },
    { count: open.length, label: t("Sự cố đang mở", "Open incidents"), hint: staff ? t("Kiểm tra và xử lý trong phạm vi LAB", "Review and resolve within LAB scope") : t("Theo dõi báo cáo của bạn", "Track your incident reports"), tab: "incidents", icon: ShieldAlert, tone: "danger" },
  ];
  const tools = staff ? [
    { icon: Wrench, tab: "maintenance", label: t("Bảo trì và hiệu chuẩn", "Maintenance and calibration"), detail: t("Lịch công việc và các booking bị ảnh hưởng", "Jobs and affected bookings") },
    { icon: Package, tab: "stock", label: t("Kho vật tư", "Materials inventory"), detail: t("Nhập, xuất và đối chiếu số lượng", "Receipts, issues and stock counts") },
  ] : [
    { icon: GraduationCap, tab: "teaching", label: t("Lớp học phần", "Course groups"), detail: t("Chuẩn bị và theo dõi buổi thực hành", "Prepare and follow practical sessions") },
    { icon: CheckCircle2, tab: "profile", label: t("Hồ sơ và điều kiện sử dụng", "Profile and access prerequisites"), detail: t("Kiểm tra thông tin và chứng nhận đào tạo", "Review details and training certificates") },
  ];
  return <section className="lab-workspace lab-home workspace-home" aria-labelledby="workspace-title">
    <header className="lab-page-heading home-welcome"><div><span className="workspace-overline">{roleLabels[user.role]} · {t("Không gian làm việc", "Workspace")}</span><h1 id="workspace-title">{t(`Chào ${user.fullName}.`, `Hello, ${user.fullName}.`)}</h1><p>{staff ? t("Điều phối LAB từ một nơi: ưu tiên yêu cầu cần xử lý, buổi sử dụng sắp tới và công việc vận hành.", "Coordinate the LAB in one place: review requests, upcoming sessions and operational tasks.") : t("Chuẩn bị cho buổi sử dụng tiếp theo. Tìm tài nguyên, kiểm tra điều kiện và theo dõi từng bước đặt lịch.", "Prepare for your next session. Find resources, check access prerequisites and track your bookings.")}</p></div><button className="primary-button" onClick={() => onNavigate(staff ? "bookings" : "smart_calendar")}><CalendarDays size={18} aria-hidden="true" />{staff ? t("Xử lý lịch đặt", "Manage bookings") : t("Đặt lịch mới", "New booking")}</button></header>
    <form className="workspace-search" onSubmit={event => { event.preventDefault(); onSearch(String(new FormData(event.currentTarget).get("query") || "").trim()); }}><Search size={20} aria-hidden="true" /><label className="sr-only" htmlFor="workspace-search">{t("Tìm tài nguyên", "Find a resource")}</label><input type="search" id="workspace-search" name="query" placeholder={t("Tìm phòng, thiết bị hoặc mã tài nguyên…", "Find a room, equipment or resource code…")} maxLength={120} /><button className="secondary-button">{t("Tra cứu", "Search")}<ArrowRight size={16} aria-hidden="true" /></button></form>
    {loading ? <div className="home-loading" role="status"><span>{t("Đang cập nhật lịch và công việc LAB…", "Updating LAB bookings and work…")}</span><div className="home-skeleton-grid" aria-hidden="true">{[0, 1, 2, 3].map(id => <div key={id} />)}</div></div> : error ? <div className="home-error" role="alert"><ShieldAlert size={22} aria-hidden="true" /><div><strong>{t("Chưa tải được đầy đủ dữ liệu", "Some data could not be loaded")}</strong><p>{t("Tải lại để xem số liệu và công việc hiện tại.", "Retry to view current figures and tasks.")}</p></div><button className="secondary-button" onClick={onRetry}>{t("Thử lại", "Retry")}</button></div> : <>
      <section className="home-attention"><div className="lab-section-heading"><h2>{t("Cần theo dõi", "Needs attention")}</h2><span className="home-scope">{staff ? t("Trong phạm vi được phân công", "Within your assigned scope") : t("Dữ liệu của bạn", "Your records")}</span></div><div className="home-attention-grid">{attention.map(({ count, label, hint, tab, icon: Icon, tone }) => <button key={label} className={`home-attention-card ${count > 0 ? `has-items tone-${tone}` : ""}`} onClick={() => onNavigate(tab)}><span className="home-attention-top"><Icon size={18} aria-hidden="true" /><ArrowRight size={16} aria-hidden="true" /></span><strong>{count}</strong><span className="home-attention-label">{label}</span><small>{hint}</small></button>)}</div></section>
      <div className="home-main-grid"><section className="home-panel home-sessions"><div className="lab-section-heading"><div><span className="workspace-overline">{t("Lịch sử dụng", "Session schedule")}</span><h2>{t("Sắp diễn ra", "Coming up")}</h2></div><button className="table-action" onClick={() => onNavigate("smart_calendar")}>{t("Mở lịch", "Open calendar")}<ArrowRight size={16} aria-hidden="true" /></button></div>
        {upcoming.length ? <div className="home-session-list">{upcoming.slice(0, 5).map(row => <button key={row.id} className="home-session" onClick={() => onNavigate("bookings")}><span className="home-session-icon"><CalendarDays size={21} aria-hidden="true" /></span><span className="home-session-info"><strong>{row.resource?.name || row.title}</strong><time dateTime={row.startAt}>{formatVietnamDateTime(row.startAt)} — {formatVietnamDateTime(row.endAt)}</time><small>{row.title}{staff && row.requestedBy?.fullName ? ` · ${row.requestedBy.fullName}` : ""}</small><span className="home-next-action">{row.status === "CHECKED_OUT" ? t("Tiếp theo: ghi nhận tình trạng và hoàn trả", "Next: record condition and return") : t("Tiếp theo: kiểm tra điều kiện và bàn giao với cán bộ LAB", "Next: verify prerequisites and hand over with LAB staff")}</span></span><span className={`home-booking-state ${row.status === "CHECKED_OUT" ? "in-use" : ""}`}>{row.status === "CHECKED_OUT" ? t("Đang sử dụng", "In use") : t("Đã xác nhận", "Confirmed")}</span><ArrowRight size={16} aria-hidden="true" /></button>)}</div> : <div className="home-empty"><CalendarDays size={32} aria-hidden="true" /><h3>{t("Chưa có buổi sử dụng sắp tới", "No upcoming sessions")}</h3><p>{staff ? t("Các lịch đã xác nhận sẽ xuất hiện tại đây để bạn chuẩn bị bàn giao.", "Confirmed bookings will appear here to help you prepare handover.") : t("Bắt đầu bằng việc tìm tài nguyên phù hợp và chọn thời gian trống.", "Start by finding a suitable resource and an available time.")}</p><button className="secondary-button" onClick={() => onNavigate("resources")}>{t("Khám phá phòng và thiết bị", "Browse rooms and equipment")}<ArrowRight size={16} aria-hidden="true" /></button></div>}
      </section><aside className="home-panel home-tools"><span className="workspace-overline">{t("Truy cập nhanh", "Quick access")}</span><h2>{t("Công việc liên quan", "Related work")}</h2>{tools.map(({ icon: Icon, tab, label, detail }) => <button className="home-tool" key={tab} onClick={() => onNavigate(tab)}><Icon size={20} aria-hidden="true" /><span><strong>{label}</strong><small>{detail}</small></span><ArrowRight size={16} aria-hidden="true" /></button>)}<button className="home-tool" onClick={() => onNavigate("incidents")}><ShieldAlert size={20} aria-hidden="true" /><span><strong>{t("Báo cáo sự cố", "Report an incident")}</strong><small>{t("Ghi nhận bất thường và theo dõi xử lý", "Record issues and track their resolution")}</small></span><ArrowRight size={16} aria-hidden="true" /></button><div className="home-guidance"><CheckCircle2 size={18} aria-hidden="true" /><p>{t("Lịch xác nhận chưa thay thế kiểm tra điều kiện. Hãy đọc hướng dẫn và phối hợp với cán bộ LAB trước khi sử dụng.", "A confirmed booking does not replace prerequisite checks. Review instructions and coordinate with LAB staff before use.")}</p></div></aside></div>
      <section className="home-panel home-notices"><div className="lab-section-heading"><div><span className="workspace-overline">{t("Cập nhật của bạn", "Your updates")}</span><h2>{t("Thông báo gần đây", "Recent notifications")}</h2></div><button className="table-action" onClick={() => onNavigate("escalations")}>{t("Xem tất cả", "View all")}<ArrowRight size={16} aria-hidden="true" /></button></div>{recent.length ? <div className="home-notice-list">{recent.map(row => <button key={row.id} className="home-notice" onClick={() => onNavigate("escalations")}><Bell size={18} aria-hidden="true" /><span><strong>{row.title}{!row.readAt && <span className="home-unread">{t("Mới", "New")}</span>}</strong><span>{row.message}</span><time dateTime={row.createdAt}>{formatVietnamDateTime(row.createdAt)}</time></span><ArrowRight size={16} aria-hidden="true" /></button>)}</div> : <p className="home-notices-empty">{t("Bạn chưa có thông báo mới. Kết quả đặt lịch và cập nhật vận hành sẽ xuất hiện tại đây.", "No notifications yet. Booking outcomes and operational updates will appear here.")}</p>}</section>
      <p className="home-time-note">{t("Lịch hiển thị theo giờ Việt Nam · UTC+07:00", "Times shown in Vietnam time · UTC+07:00")}</p>
    </>}
  </section>;
}
